import "./globals.css";
import { Suspense } from "react";

export const metadata = {
  title: "Cookie",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body>
        <Suspense>
          {children}
        </Suspense>
      </body>
    </html>
  );
}
